#!/bin/bash



# Search for "success" inside files and move them to success folder
if [ ! -d "success" ]
then
    mkdir success
fi

if [ ! -d "archive" ]
then
    mkdir archive
fi

for file in *
do
	if grep -q "success" "$file"
		then
       		 mv "$file" success/
        	echo "Moved $file to success folder."

    	elif [ "$file" != "success" ] 
         	then
         	mv "$file" archive/
         	echo "Moved $file to archive folder."
     	fi
    
done
